import Head from 'next/head'
import Image from 'next/image' 
import navLogo from '../public/assets/navLogo.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matt | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={navLogo} alt='/' />
    </div>
  )
}
