import Head from 'next/head'
import Main from '../components/Main';
import About from '../components/About'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matt | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
    </div>
  )
}
